OnlineRecritmentSystem/OnlineRecritmentSystem/Controllers/EmployeerLoginController.cs
using OnlineRecritmentSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineRecritmentSystem.Controllers
{
    public class EmployeerLoginController : Controller
    {
        // GET: EmployeerLogin
        public ActionResult EmployeerLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult EmployeerLogin(int? UserId, string Password)
        {
            OnlineRecrutimentModel tr = new OnlineRecrutimentModel();
            if (ModelState.IsValid)
            {
                var obj = tr.Firsttimeusers.Where(a => a.UserId == UserId && a.Password.Equals(Password)).FirstOrDefault();
                if (obj != null)
                {
                    Session["UserID"] = obj.UserId.ToString();
                    Session["UserName"] = obj.Name.ToString();
                    return RedirectToAction("ReqApplication");
                    //return Content($"Welcome {obj.Name.ToString()}");
                }
            }
            return View(UserId);
        }

        public ActionResult EmployeerDetails()
        {
            return View();
        }

        public ActionResult ReqApplication()
        {
            OnlineRecrutimentModel db = new OnlineRecrutimentModel();
            var res = db.JobSeekers.ToList();
            return View(res);
        }
        [HttpPost]
        public ActionResult ReqApplication(JobSeeker obj)
        {
            //if(obj.Status== "Accepted")
            //    {
            //    ViewBag.job applied succesfully;
            //    return RedirectToAction("")
            //}
            return View();
        }
    }
}

OnlineRecritmentSystem/OnlineRecritmentSystem/Controllers/msgController.cs
using OnlineRecritmentSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineRecritmentSystem.Controllers
{
    public class msgController : Controller
    {
        OnlineRecrutimentModel tr = new OnlineRecrutimentModel();
        // GET: msgS
        public ActionResult Index()
        {
            //  return View();
           
            return Content("successfully Approved");
        }
    }
}

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/EmployeerLogin/EmployeerDetails.cshtml
@{
    ViewBag.Title = "EmployeerDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EmployeerDetails</h2>

<a href="~/Employers/Index">EmployeerDetails</a>

<body style="background-color:aliceblue"></body>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/EmployeerLogin/EmployeerLogin.cshtml
@model OnlineRecritmentSystem.Models.Firsttimeuser

@{
    ViewBag.Title = "EmployeerLogin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EmployeerLogin</h2>

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body, html {
            height: 100%;
        }

        .bg {
            /* The image used */
            background-image: url('../../Image/Login.jpg');
            /* Full height */
            height: 100%;
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

    <!-- Custom fonts for this template-->
    <link href="~/Scripts/User/all.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="~/Scripts/User/sb-admin.css" rel="stylesheet">
</head>
<body class="bg">
    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Login</div>
            <div class="card-body">
                <form method="post">
                    <div class="form-group">
                        <div class="form-label-group">
                            <input type="text" id="UserId" class="form-control" placeholder="UserId" required="required" name="UserId" autofocus="autofocus">
                            <label for="UserId">UserId</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-label-group">
                            <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="Password" required="required">
                            <label for="inputPassword">Password</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" value="remember-me">
                                Remember Password
                            </label>
                        </div>
                    </div>
                    <button class="btn-primary btn-block">Login</button>
                </form>
                <div class="text-center">
                    <a href="~/Home/Register">Register an Account</a>

                    <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Scripts/User/jquery.min.js"></script>
    <script src="~/Scripts/User/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/User/jquery.easing.min.js"></script>
</body>
</html>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/EmployeerLogin/ReqApplication.cshtml
@model IEnumerable<OnlineRecritmentSystem.Models.JobSeeker>

@{
    ViewBag.Title = "ReqApplication";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ReqApplication</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<form action="EmployerLogin/ReqApplication" method="post">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emailid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.photo)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Experience)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreferredJobLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Skills)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dateofapplication)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Resume)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                <label name="Name">@item.Name</label>
            </td>
            <td>
                <label name="Emailid">@item.Emailid</label>
            </td>
            <td>
                <label name="@item.MobileNo">@item.MobileNo</label>
            </td>
            <td>
                <label name="@item.Location">@item.Location</label>
            </td>
            @*<td>
            <label name="@item.photo">@item.photo</label>
        </td>*@
            <td>
                <label name="@item.Position">@item.Position</label>
            </td>
            <td>
                <label name="@item.Experience">@item.Experience</label>
            </td>
            <td>
                <label name="@item.PreferredJobLocation">@item.PreferredJobLocation</label>
            </td>
            <td>
                <label name="@item.Skills">@item.Skills</label>
            </td>
            <td>
                <label name="@item.Dateofapplication">@item.Dateofapplication</label>
            </td>
            @*<td>
            <label name="@item.Resume">@item.Resume</label>
        </td>*@


            <td>
                <select name=@item.Status>
                    <option value="Status">@item.Status</option>
                    <option value="Accepted">Accepted</option>
                    <option value="Rejected">Rejected</option>
                </select>
            </td>
            
            <td>
                @Html.ActionLink("Save", "Index", "msg")@*<button class="btn btn-primary">Save</button>*@
            </td>
        </tr>
        }
    </table>
   
</form>