OnlineRecritmentSystem/OnlineRecritmentSystem/Controllers/JobSeekersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRecritmentSystem.Models;

namespace OnlineRecritmentSystem.Controllers
{
    public class JobSeekersController : Controller
    {
        private OnlineRecrutimentModel db = new OnlineRecrutimentModel();

        // GET: JobSeekers
        public ActionResult Index()
        {
            return View(db.JobSeekers.ToList());
        }

        //[HttpPost]
        //public ActionResult Index(JobSeeker jsk)
        //{
        //    OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
        //    return View();




        //    //var query = from b in onm.JobSeekers.ToList()
        //    //            where b.Experience == div || b.Skills==skill || b.PreferredJobLocation == loc || b.Position == position 
        //    //            select b;
        //    //return View(query);
        //}
        // GET: JobSeekers
        //public ActionResult Position()
        //{
        //    return View(db.JobSeekers.ToList());
        //}

        //[HttpPost]
        //public ActionResult Position(string div, string Position)
        //{
        //    OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
        //    var query = from b in onm.JobSeekers.ToList()
        //                where b.Position == div 
        //                select b;
        //    return View(query);
        //}

        //[HttpPost]
        //public ActionResult Index()
        //{
        //    OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
        //    var query = from b in onm.JobSeekers.ToList()
        //                where b.Experience == div
        //                select b;
        //    return View(query);
        //}
        //// GET: JobSeekers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobSeeker jobSeeker = db.JobSeekers.Find(id);
            if (jobSeeker == null)
            {
                return HttpNotFound();
            }
            return View(jobSeeker);
        }

        // GET: JobSeekers/Create
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Password,Emailid,MobileNo,Location,photo,Position,Experience,PreferredJobLocation,Skills,Dateofapplication,Resume")] JobSeeker jobSeeker)
        {
            if (ModelState.IsValid)
            {
                jobSeeker.Status = "Requested";
                db.JobSeekers.Add(jobSeeker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(jobSeeker);
        }

        // GET: JobSeekers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobSeeker jobSeeker = db.JobSeekers.Find(id);
            if (jobSeeker == null)
            {
                return HttpNotFound();
            }
            return View(jobSeeker);
        }

        // POST: JobSeekers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,Password,Emailid,MobileNo,Location,photo,Position,Experience,PreferredJobLocation,Skills,Dateofapplication,Resume")] JobSeeker jobSeeker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobSeeker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(jobSeeker);
        }

    
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //// GET: JobSeekers/Details/5
        public ActionResult Search()
        {
            return RedirectToAction("Capgemini", "JobsSearch");

        }
       

    }
}

OnlineRecritmentSystem/OnlineRecritmentSystem/Controllers/JobsSearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineRecritmentSystem.Models;

namespace OnlineRecritmentSystem.Controllers
{
    public class JobsSearchController : Controller
    {
        private OnlineRecrutimentModel db = new OnlineRecrutimentModel();

        // GET: JobsSearch
        public ActionResult Index()
        {
            return View(db.Jobs.ToList());
        }

        // GET: JobsSearch/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: JobsSearch/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobsSearch/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Jobid,Designation,Company,ComapnyName,Salary")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(job);
        }

        // GET: JobsSearch/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: JobsSearch/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Jobid,Designation,Company,ComapnyName,Salary")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: JobsSearch/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: JobsSearch/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        public ActionResult Index(string Company, string skill, int id)
        {
            OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
            var query = from b in onm.Jobs.ToList()
                        where b.ComapnyName == Company || b.Designation == skill || b.Jobid == id
                        select b;
            return View(query);
        }
        //[HttpPost]
        //public ActionResult Index(int id, string skill, string Company)
        //{

        //    if (Session["id"] != null && Session["skill"] != null && Session["Company"].ToString() == "Index")
        //    {
        //        if (id == 0)
        //        {
        //            OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
        //            var query = from b in onm.Jobs.ToList()
        //                where  b.Jobid == id 
        //                select b;
        //            return View(query);
        //        }
        //        else if(skill==null)
        //        {
        //            OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
        //            var query = from b in onm.Jobs.ToList()
        //                        where b.Designation == skill
        //                        select b;
        //            return View(query);
        //        }
        //        else if(Company==null)
        //        {
        //            OnlineRecrutimentModel onm = new OnlineRecrutimentModel();
        //            var query = from b in onm.Jobs.ToList()
        //                        where b.Company == Company
        //                        select b;
        //            return View(query);
        //        }
        //else
        //{
        //    return RedirectToAction("", " ");
        //}
        public ActionResult Capgemini()
        {
            return View();
        }
        public ActionResult Tcs()
        {
            return View();
        }
        public ActionResult Hcl()
        {
            return View();
        }
        public ActionResult Wipro()
        {
            return View();
        }

    }
        }
    

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Capgemini.cshtml
@{
    ViewBag.Title = "Capgemini";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Capgemini</h2>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <link href="bootstrap.min.css" rel="stylesheet" />
    <link href="bootstrap.css" rel="stylesheet" />
</head>
<body>

    <div class="row">
        <div>
            <label>Search by Location</label>
            <input type="text" id="location"/>
        </div>
        <div>
            <button class="btn-default" onclick="search()">Search</button>
        </div>
    </div>
    <div id="Maindiv">
        <div class="inn_div" id="hyderabad">
            <h2>Capgemini India Service Pvt Ltd.</h2>
            <h4>Dotnet with Cloud</h4>
            <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
            <address>

                No. of requirement: 4<br />

                Position: Tech Support<br />

                Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

                CTC: 5 to 6 LPA<br />
                 Location : hyderbad<br />

                PreferredJobLocation : Banglore<br />
                Looking for immediate joiners only<br />

                Work Experience:<br />

                1 to 2 years experience in implementing/supporting a Payment Domain application.
                Knowledge / working skill in MS SQL Database concepts.
                Knowledge of .net .<br />
            </address>
            <div>
                @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />
            </div>
        </div>
        <div class="inn_div" id="chennai">

            <h2>Tcs India Service Pvt Ltd.</h2>
            <h4>Full stack java developer</h4>
            <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
            <address>

                No. of requirement: 10<br />

                Position: Software Developer<br />

                Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

                CTC: 3 to 4 LPA<br />
                 Location : chennai<br />

                PreferredJobLocation : Banglore<br />
                Looking for immediate joiners only<br />

                Work Experience:<br />
                Location : Hyderabad
                1 to 2 years experience in implementing/supporting a Payment Domain application.
                Knowledge / working skill in MS SQL Database concepts.
                Knowledge of java .<br />
            </address>
        </div>
        <div>

            @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />


        </div>
        <div class="inn_div" id="pune">
            <h2>Hcl India Service Pvt Ltd.</h2>
            <h4>Dotnet with Cloud</h4>
            <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
            <address>

                No. of requirement: 5<br />

                Position: Analyst<br />

                Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

                CTC: 2 to 3 LPA<br />

                Looking for immediate joiners only<br />

                 Location : pune<br />

                PreferredJobLocation : Hyderbad<br />
                Work Experience:<br />
                Location : pune <br />
                1 to 2 years experience in implementing/supporting a Payment Domain application.
                Knowledge / working skill in MS SQL Database concepts.
                Knowledge of .net .<br />
            </address>
        </div>
        <div>

            @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />


        </div>
        <div class="inn_div" id="mumbai">
            <h2>Wipro India Service Pvt Ltd.</h2>
            <h4>Dotnet with Cloud</h4>
            <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
            <address>

                No. of requirement: 4<br />

                Position:  Support Role<br />

                Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

                CTC: 3 to 4 LPA<br />

                Location : mumbai<br />

                PreferredJobLocation : Banglore<br />


                Looking for immediate joiners only<br />

                Work Experience:<br />
                Location : Mumbai <br />
                1 to 2 years experience in implementing/supporting a Payment Domain application.
                Knowledge / working skill in MS SQL Database concepts.
                 .<br />
            </address>
        </div>
        <div>

            @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />


        </div>
    </div>
</body>
</html>

@section scripts{
    <script>
        function search() {
            var loc = document.getElementById("location").value;

            var div = document.getElementById("Maindiv").querySelectorAll("div");           
            for (i = 0; i < div.length; i++) {
                    div[i].style.display = "block";
                }
            for (i = 0; i < div.length; i++) {
                if (div[i].id != loc.toLowerCase()) {
                    div[i].style.display = "none";
                };
            }
        }
    </script>
    
    }

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Create.cshtml
@model OnlineRecritmentSystem.Models.Job

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Jobid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Jobid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Jobid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ComapnyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComapnyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ComapnyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Delete.cshtml
@model OnlineRecritmentSystem.Models.Job

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.ComapnyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComapnyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Details.cshtml
@model OnlineRecritmentSystem.Models.Job

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.Company)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.ComapnyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComapnyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Jobid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Edit.cshtml
@model OnlineRecritmentSystem.Models.Job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Jobid)

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ComapnyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComapnyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ComapnyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Hcl.cshtml
@{
    ViewBag.Title = "Hcl";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Hcl</h2>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <link href="bootstrap.min.css" rel="stylesheet" />
    <link href="bootstrap.css" rel="stylesheet" />
</head>
<body>
    <h2>Hcl India Service Pvt Ltd.</h2>
    <h4>Dotnet with Cloud</h4>
    <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
    <address>

        No. of requirement: 4<br />

        Position: Tech Support<br />

        Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

        CTC: 5 to 6 LPA<br />

        Looking for immediate joiners only<br />

        Work Experience:<br />

        1 to 2 years experience in implementing/supporting a Payment Domain application.
        Knowledge / working skill in MS SQL Database concepts.
        Knowledge of .net .<br />
    </address>
    <div>

        @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />


    </div>
</body>
</html>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Index.cshtml
@model IEnumerable<OnlineRecritmentSystem.Models.Job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm())
{

    <h3>
        <select class="form-control" id="exampleFormControlSelect1">
            <option value="Designation">Company</option>
            <option value="Experience">Skill</option>
            <option value="Profession">id</option>
           
        </select>
        <input type="text" name="Company" placeholder="Company" />
        <input type="text" name="skill" placeholder="Skill"/>
        <input type="text" name="id"  placeholder="id"/>
        

        <input type="submit" value="Search" class="btn btn-info" />
    </h3>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Designation)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Company)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ComapnyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Designation)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Company)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.ComapnyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Jobid }) |
                @Html.ActionLink("Details", "Details", new { id = item.Jobid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Jobid })
            </td>
        </tr>
    }

</table>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Tcs.cshtml
@{
    ViewBag.Title = "Tcs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tcs</h2>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <link href="bootstrap.min.css" rel="stylesheet" />
    <link href="bootstrap.css" rel="stylesheet" />
</head>
<body>
    <h2>Tcs India Service Pvt Ltd.</h2>
    <h4>Dotnet with Cloud</h4>
    <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
    <address>

        No. of requirement: 4<br />

        Position: Tech Support<br />

        Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

        CTC: 5 to 6 LPA<br />

        Looking for immediate joiners only<br />

        Work Experience:<br />

        1 to 2 years experience in implementing/supporting a Payment Domain application.
        Knowledge / working skill in MS SQL Database concepts.
        Knowledge of .net .<br />
    </address>
    <div>

        @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />


    </div>
</body>
</html>

OnlineRecritmentSystem/OnlineRecritmentSystem/Views/JobsSearch/Wipro.cshtml
@{
    ViewBag.Title = "Wipro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Wipro</h2>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <link href="bootstrap.min.css" rel="stylesheet" />
    <link href="bootstrap.css" rel="stylesheet" />
</head>
<body>
    <h2>Wipro India Service Pvt Ltd.</h2>
    <h4>Dotnet with Cloud</h4>
    <h4> Urgently required of Dot Net Support Engineer at Pokhran-Thane W.</h4><br />
    <address>

        No. of requirement: 4<br />

        Position: Tech Support<br />

        Qualification: B.E/B.Tech/B.Sc. (Computers)/BCA/MCA<br />

        CTC: 5 to 6 LPA<br />

        Looking for immediate joiners only<br />

        Work Experience:<br />

        1 to 2 years experience in implementing/supporting a Payment Domain application.
        Knowledge / working skill in MS SQL Database concepts.
        Knowledge of .net .<br />
    </address>
    <div>

        @Html.ActionLink("ApplyJob", "Create", "JobSeekers", routeValues: null, htmlAttributes: new { id = "regLink" })<br />


    </div>
</body>
</html>